# Pre-commit設定ファイル
# 自動フォーマッターをコミット時に実行し、GitHub Actionでのフォーマットエラーを防ぐ

repos:
  # Black - Python コードフォーマッター
  - repo: https://github.com/psf/black
    rev: '23.12.0'  # requirements.txtと同じバージョン
    hooks:
      - id: black
        language_version: python3.12
        args: ['--line-length=88']

  # isort - import文の並び替え
  - repo: https://github.com/pycqa/isort
    rev: '5.13.2'  # requirements.txtと同じバージョン
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=88']

  # flake8 - PEP8準拠チェック
  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # requirements.txtと同じバージョン
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--extend-ignore=E203,W503']

  # MyPy - 型チェック
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'  # requirements.txtと同じバージョン
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: ['--config-file=setup.cfg']

  # 一般的なファイルチェック
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

# 自動修正が行われた場合のコミット失敗設定
# fail_fast: true により、最初のフックが失敗した時点で停止
fail_fast: true

# 除外するファイル・ディレクトリ
exclude: |
  (?x)^(
      migrations/.*|
      \.venv/.*|
      venv/.*|
      build/.*|
      dist/.*|
      node_modules/.*|
      \.git/.*|
      tests/.*
  )$
